server:
  port: 9094

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    service-url:
      #defaultZone: http://eureka-0.eureka-service.default.svc.cluster.local:8761/eureka
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: ORDER-SERVICE
  data:
    mongodb:
      #uri: mongodb+srv://admin:eusou100@pedidodb.27xpu.mongodb.net/?retryWrites=true&w=majority&appName=pedidodb
      #host: atlas-cluster.mqdj7js.mongodb.net
      host: localhost
      port: 27017
      database: pedidodb
      authentication-database: admin
      username: admin
      password: eusou100
      repositories:
        enabled: true
